name: Docker

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-dev[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Set up Docker Buildx ğŸ³
        uses: docker/setup-buildx-action@v1

      - id: get_version
        run: echo "::set-output name=version::$(<./src/bfio/VERSION)"

      - run: echo ${{ steps.get_version.outputs.version }}

      - name: Install Quemu emulator
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish Base Container ğŸ³
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./docker/base/Dockerfile
          push: false
          tags: polusai/bfio:${{ steps.get_version.outputs.version }}

      - name: Publish Tensorflow Container ğŸ³
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./docker/tensorflow/Dockerfile
          push: false
          tags: polusai/bfio:${{ steps.get_version.outputs.version }}-tensorflow

      - name: Publish ImageJ Container ğŸ³
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./docker/imagej/Dockerfile
          push: false
          tags: polusai/bfio:${{ steps.get_version.outputs.version }}-imagej
